version: "3.2"
services:
  php:
    build:
      context: .
    image: webuxmotion/palermocms:1.0.0
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=palermocms-mysql-app
      - MYSQL_USER=palermocmsuser
      - MYSQL_PASSWORD=palermocmspass
      - MYSQL_DB=palermocms_db
    volumes:
      - ./:/var/www/html/
    ports:
      - "50001:80"
    container_name: palermocms-php-app
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=palermocmsuser
      - MYSQL_PASSWORD=palermocmspass
      - MYSQL_DATABASE=palermocms_db
    container_name: palermocms-mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "50002:80"
    environment:
      - PMA_HOST=palermocms-mysql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: palermocms-phpmyadmin-app
networks:
  frontend:
  backend:
